/**
 * SystemEvent emitter service (T017).
 *
 * Creates, queries, and acknowledges system-level events generated by
 * autonomous agents. Events surface on the admin dashboard for operator
 * visibility and can be filtered by type, severity, and acknowledgement state.
 */

import type { SystemEvent, Severity, Prisma } from '@prisma/client';
import { prisma } from '../../models/index.js';
import logger from '../../lib/logger.js';

const log = logger.withContext({ service: 'systemEventEmitter' });

/** Parameters for emitting a new system event. */
export interface EmitEventParams {
  /** Machine-readable event type (e.g. "infrastructure_auto_heal"). */
  type: string;
  /** Severity classification. */
  severity: Severity;
  /** Human-readable event description. */
  message: string;
  /** Arbitrary structured metadata about the event. */
  metadata: Record<string, unknown>;
  /** Optional name of the agent that generated this event. */
  agentName?: string;
}

/**
 * Creates a new SystemEvent record in the database.
 *
 * @param params - The event data to persist.
 * @returns The created SystemEvent record.
 */
export async function emitEvent(params: EmitEventParams): Promise<SystemEvent> {
  try {
    const event = await prisma.systemEvent.create({
      data: {
        type: params.type,
        severity: params.severity,
        message: params.message,
        metadata: params.metadata as Prisma.InputJsonValue,
        agentName: params.agentName ?? null,
      },
    });

    log.info('System event emitted', {
      id: event.id,
      type: params.type,
      severity: params.severity,
      agentName: params.agentName,
    });

    return event;
  } catch (error) {
    log.error('Failed to emit system event', {
      type: params.type,
      severity: params.severity,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}

/** Filters for querying system events. */
export interface GetEventsFilters {
  /** Filter by event type. */
  type?: string;
  /** Filter by severity level. */
  severity?: Severity;
  /** Filter by acknowledgement status. */
  acknowledged?: boolean;
  /** Only return events on or after this date. */
  startDate?: Date;
  /** Only return events on or before this date. */
  endDate?: Date;
  /** Page number (1-based). Defaults to 1. */
  page?: number;
  /** Results per page. Defaults to 25. */
  limit?: number;
}

/** Paginated result set of system events. */
export interface GetEventsResult {
  /** The matching system event records. */
  events: SystemEvent[];
  /** Total count of records matching the filters (for pagination). */
  total: number;
}

/**
 * Retrieves system events with optional filters and pagination.
 *
 * @param filters - Optional filters for type, severity, acknowledgement, date range, and pagination.
 * @returns Paginated list of matching system events and the total count.
 */
export async function getEvents(filters?: GetEventsFilters): Promise<GetEventsResult> {
  try {
    const page = filters?.page ?? 1;
    const limit = filters?.limit ?? 25;
    const skip = (page - 1) * limit;

    const where: Prisma.SystemEventWhereInput = {
      ...(filters?.type ? { type: filters.type } : {}),
      ...(filters?.severity ? { severity: filters.severity } : {}),
      ...(filters?.acknowledged !== undefined
        ? { acknowledged: filters.acknowledged }
        : {}),
      ...(filters?.startDate || filters?.endDate
        ? {
            timestamp: {
              ...(filters?.startDate ? { gte: filters.startDate } : {}),
              ...(filters?.endDate ? { lte: filters.endDate } : {}),
            },
          }
        : {}),
    };

    const [events, total] = await Promise.all([
      prisma.systemEvent.findMany({
        where,
        orderBy: { timestamp: 'desc' },
        skip,
        take: limit,
      }),
      prisma.systemEvent.count({ where }),
    ]);

    log.debug('Retrieved system events', {
      total,
      page,
      limit,
      returned: events.length,
    });

    return { events, total };
  } catch (error) {
    log.error('Failed to retrieve system events', {
      filters,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}

/**
 * Marks a system event as acknowledged by an admin user.
 *
 * @param id - The UUID of the SystemEvent to acknowledge.
 * @param acknowledgedBy - Identifier of the admin user acknowledging the event.
 * @returns The updated SystemEvent record.
 */
export async function acknowledgeEvent(
  id: string,
  acknowledgedBy: string,
): Promise<SystemEvent> {
  try {
    const event = await prisma.systemEvent.update({
      where: { id },
      data: {
        acknowledged: true,
        acknowledgedBy,
        acknowledgedAt: new Date(),
      },
    });

    log.info('System event acknowledged', {
      id,
      acknowledgedBy,
      type: event.type,
    });

    return event;
  } catch (error) {
    log.error('Failed to acknowledge system event', {
      id,
      acknowledgedBy,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}
